# ---- Base Layer -----
FROM node:alpine AS base
WORKDIR /app 

# ---- Dependencies Layer (cached) ----
FROM base AS deps 
COPY package.json package-lock.json ./
RUN npm install

# ---- Build Layer ----
FROM base AS builder
COPY --from=deps /app/node_modules  ./node_modules
COPY . .
RUN npm run build

# ---- Production Layer ----
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=Production

COPY --from=builder /app
    